default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: worker
  password: work

development:
  <<: *default
  database: api-platform_development

test:
  <<: *default
  database: api-platform_test

production:
  <<: *default
  database: api-platform_production
  username: api-platform
  password: <%= ENV['API-PLATFORM_DATABASE_PASSWORD'] %>
